# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Dessert')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Drink')),
                ('mainCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.MainCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SideDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='salad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Salad'),
        ),
        migrations.AddField(
            model_name='menu',
            name='sideDish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SideDish'),
        ),
    ]
