# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('CHILE', 'CHILE'), ('MEXICO', 'MEXICO'), ('UNASSIGNED', 'UNASSIGNED')], max_length=11)),
                ('address', models.CharField(max_length=255)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('user_slack', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
